# Numpy 

Numpy is a library which provides support for large, homogeneous, multi-dimensional arrays and matrices

In [9]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/fc/84/7f801a42a67b9772a883223a0a1e12069a14626c81a732bd70aac57aebc1/numpy-2.2.2-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 217.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.8 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 327.7 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 294.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 3.6 MB/s eta 0:00:04
   - -------------------------------------- 0.6/12.6 MB 7.4 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/12.6 MB 10.6 MB/s eta 0:00:02
   ------ -------------------


[notice] A new release of pip is available: 23.2.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
#import numpy
import numpy as np

# Creating an array from a list

In [12]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [13]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [14]:
type(arr1)

numpy.ndarray

# Using arrange to create an array

The difference between array and arrange is that array takes in a list and turns it into an array, whereas arange creates an array from a range of numbers

In [15]:
arr2 = np.arange(10, 20, 1) #(start, end, step size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Multidimensional arrays


## Combining two list - Two Dimensional arrays


In [16]:
list2 = [40,50,60]

list3 = [list1, list2]

arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
#shows rows and columns
arr3.shape

(2, 3)

# Three-dimensional arrays
