# Numpy 

Numpy is a library which provides support for large, homogeneous, multi-dimensional arrays and matrices

In [9]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/fc/84/7f801a42a67b9772a883223a0a1e12069a14626c81a732bd70aac57aebc1/numpy-2.2.2-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 217.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.8 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 327.7 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 294.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 3.6 MB/s eta 0:00:04
   - -------------------------------------- 0.6/12.6 MB 7.4 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/12.6 MB 10.6 MB/s eta 0:00:02
   ------ -------------------


[notice] A new release of pip is available: 23.2.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
#import numpy
import numpy as np

# Creating an array from a list

In [4]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [5]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [6]:
type(arr1)

numpy.ndarray

# Using arrange to create an array

The difference between array and arrange is that array takes in a list and turns it into an array, whereas arange creates an array from a range of numbers

In [7]:
arr2 = np.arange(10, 20, 1) #(start, end, step size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Multidimensional arrays


## Combining two list - Two Dimensional arrays


In [8]:
list2 = [40,50,60]

list3 = [list1, list2]

arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
#shows rows and columns
arr3.shape

(2, 3)

# Three-dimensional arrays


In [13]:
arr3dim = np.array([[[1, 2, 3], [3,4,5]], 
                     [[5,6,7], [7,8,9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [14]:
arr3dim.shape

(2, 2, 3)

## Using Arrays and Scalars

Numpy arrays (or ndarray) allows us to perform matric operations

In [16]:
list1 * 3
#lists and arrays are treated differently

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [17]:
#array multiplied by another array
arr11 = np.array(list2)

arr1 * arr11

array([ 400, 1000, 1800])

### It is possible to multiply arrays of different dimensions, but they need the same element size

In [18]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

# Create ndarrays of the following sizes:
One dimensional array with 12 elements (12,)
Two dimensional array size (3, 4)
Three dimensional array size (2, 5, 4)

In [23]:
#one dimension array with 12 elements
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
# two dimensional array size (3,4)
y = np.arange(12).reshape(3, 4) #raveling the array (using the given index order)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# three dimensional array size (2, 5, 4)
z = np.arange(40).reshape(2, 5, 4)
z
z.shape

(2, 5, 4)

In [32]:
# two dimensional array size (3, 4)
array_2d = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Accessing the values inside ndarrays

Lets take arr3 as our example, this was a 2d array

In [34]:
#how do we acccess 60?
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [36]:
arr3[1][2] # this uses indexing

60

In [37]:
#How to find the bottom row?
arr3[1]

array([40, 50, 60])

In [39]:
#last column
arr3[:,2]

array([30, 60])

In [40]:
#first row
arr3[0,:]

array([10, 20, 30])

## Statistical functions and arrays

There are a number of builtin functions we can use with numpy

In [41]:
#find the sum 
arr3.sum()

210

In [42]:
#find the sum of all columns
arr3.sum(0)

array([50, 70, 90])

In [43]:
#finding the sum of all rows
arr3.sum(1)

array([ 60, 150])

In [44]:
#find mean
arr3.mean()

35.0

In [45]:
#find standard deviation
arr3.std()

17.07825127659933

In [46]:
#find variance
arr3.var()

291.6666666666667

In [47]:
#find min value
arr3.min()

10

In [48]:
#find max value
arr3.max()

60

# Iterating through ndarrays

Simplest way to use a simple loop

In [49]:
#for a 1d array
for x in arr1:
    print(x)

10
20
30


In [50]:
#use nested loop for n-dimensional array
for dim in arr3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [52]:
#use nditter
#used in simple scenarios, but also complex ones too
#tends to be cleaner for nested loops
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


### Saving and loading in numpy

In [53]:
# TO save an array as a file
np.save('new', arr3)

In [54]:
# load the file
np.load('new.npy')

array([[10, 20, 30],
       [40, 50, 60]])

In [55]:
#saving as a txt
np.savetxt('new.txt', arr3, delimiter=',')

In [56]:
#loading a txt
np.loadtxt('new.txt', delimiter=',')

array([[10., 20., 30.],
       [40., 50., 60.]])